### ISSUE TITLE
'forks_count' error for GitLab indexer

### ISSUE THREAD

**Issue by JaroslawHryszko** [Software-Engineering-Jagiellonian/django-celery-frege#85]
`gitlab.py` regularly returns above error in logs:

```
fregepoc-celery-crawl-worker-dev      | [2023-03-15 10:52:23,030: ERROR/ForkPoolWorker-30] Task fregepoc.repositories.tasks.crawl_repos_task[211ba143-d2b3-4f54-81c7-d440dbcea97d] raised unexpected: KeyError('forks_count')
fregepoc-celery-crawl-worker-dev      | Traceback (most recent call last):
fregepoc-celery-crawl-worker-dev      |   File "/usr/local/lib/python3.10/site-packages/celery/app/trace.py", line 451, in trace_task
fregepoc-celery-crawl-worker-dev      |     R = retval = fun(*args, **kwargs)
fregepoc-celery-crawl-worker-dev      |   File "/usr/local/lib/python3.10/site-packages/celery/app/trace.py", line 734, in __protected_call__
fregepoc-celery-crawl-worker-dev      |     return self.run(*args, **kwargs)
fregepoc-celery-crawl-worker-dev      |   File "/usr/local/lib/python3.10/site-packages/celery/app/autoretry.py", line 34, in run
fregepoc-celery-crawl-worker-dev      |     return task._orig_run(*args, **kwargs)
fregepoc-celery-crawl-worker-dev      |   File "/app/fregepoc/repositories/tasks.py", line 163, in crawl_repos_task
fregepoc-celery-crawl-worker-dev      |     batch = next(iter(indexer), [])
fregepoc-celery-crawl-worker-dev      |   File "/app/fregepoc/indexers/models.py", line 211, in __iter__
fregepoc-celery-crawl-worker-dev      |     for repo_data, _id in gitlab_client.repositories():
fregepoc-celery-crawl-worker-dev      |   File "/app/fregepoc/indexers/utils/gitlab.py", line 39, in repositories
fregepoc-celery-crawl-worker-dev      |     if project['star_count'] >= self.min_stars and project['forks_count'] >= self.min_forks:
fregepoc-celery-crawl-worker-dev      | KeyError: 'forks_count' 

```

This has to be investigated as it probably has impact on number of repositories which ARE NOT analyzed.

**Comment by konradporeba** [comment]
Problem here is that the following endpoint used to get information about repo
`BASE_ENDPOINT = "https://gitlab.com/api/v4/projects"` 
includes "forks_count"  field in the response body ONLY when user is authenticated (the following env variable in .env file should be set `GITLAB_TOKEN=`) and the following parameter `simple=false` is used in the request

NOT SIMPLE Response with authenticated user:
![Screenshot 2023-04-22 at 00 22 34](https://user-images.githubusercontent.com/34138284/233743441-53971a09-5ff5-49c2-99ae-1383f9502351.png)

SIMPLE Response that is received and is causing this problem:
![Screenshot 2023-04-22 at 00 23 36](https://user-images.githubusercontent.com/34138284/233743455-b52f9827-97c7-4aa2-aefc-b566673a17df.png)

Currently logic of this indexer is as follows
```
"""Returns repository and the projects id"""
for project in chain.from_iterable(self._projects()):
    if project['star_count'] >= self.min_stars and project['forks_count'] >= self.min_forks:
```
So to solve this problem we need to do one of the following actions:

1. Always authenticate gitlab user by setting proper env variable with gitlab token
2. Remove min_forks requirement from the condition

Sources: [GitLab API docs](https://docs.gitlab.com/ee/api/projects.html#list-all-projects)
